import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { BookOpen, Globe2, Layers3, Scale } from "lucide-react";
import CodeBlock from "./CodeBlock";
import MessageActions from "./MessageActions";
const routeLabels={rag:"Document research",web:"Web research",hybrid:"Combined research"};
function sourceKey(source,index){if(source.source_type==="web")return `web:${source.url||source.title||index}`;return `document:${source.document_id||source.filename||index}:${source.page_number??""}:${source.chunk_index??""}`}
function validUrl(url){try{const parsed=new URL(url);return parsed.protocol==="https:"||parsed.protocol==="http:"}catch{return false}}
function Sources({sources}){const unique=Array.from(new Map(sources.map((source,index)=>[sourceKey(source,index),source])).values());return <details className="sources"><summary><BookOpen size={15}/> Evidence & sources <span className="source-count">{unique.length} {unique.length===1?"source":"sources"}</span></summary><div className="source-grid">{unique.map((source,index)=>{const web=source.source_type==="web";const name=web?source.title:source.filename;const url=web&&validUrl(source.url)?source.url:null;return <article className="source-card" key={sourceKey(source,index)}><div className="source-type">{web?"Web source":"Document source"}</div><div className="source-title">{url?<a href={url} target="_blank" rel="noopener noreferrer">{name||url}</a>:name||"Source"}</div><div className="source-meta">{source.page_number!=null&&<span>Page {source.page_number}</span>}{source.chunk_index!=null&&<span>Chunk {source.chunk_index}</span>}{source.score!=null&&<span>Relevance {source.score}</span>}{source.engine&&<span>{source.engine}</span>}{source.url&&<span className="source-url">{source.url}</span>}</div>{web&&source.content&&<p className="source-preview">{source.content}</p>}</article>})}</div></details>}
export default function ChatMessage({message}){const isUser=message.role==="user";const RouteIcon=message.route?.toLowerCase()==="web"?Globe2:message.route?.toLowerCase()==="hybrid"?Layers3:BookOpen;return <article className={`chat-entry ${isUser?"user":"assistant"}`}>{isUser?<div className="user-bubble">{message.content}</div>:<div><div className="answer-header"><span className="answer-mark"><Scale size={15}/></span> AskLAW {message.route&&routeLabels[message.route.toLowerCase()]&&<span style={{display:'inline-flex',alignItems:'center',gap:5,marginLeft:6,color:'#89949f',fontWeight:500}}><RouteIcon size={13}/>{routeLabels[message.route.toLowerCase()]}</span>}</div>{message.content?<div className="answer-body"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{code({className,children}){const match=/language-(\w+)/.exec(className||"");return match?<CodeBlock language={match[1]}>{String(children).replace(/\n$/,'')}</CodeBlock>:<code>{children}</code>}}}>{message.content}</ReactMarkdown></div>:<div className="streaming-line"><span className="pulse-dot"/> Generating answer…</div>}{message.sources?.length>0&&<Sources sources={message.sources}/>} {message.isComplete&&message.content&&<MessageActions content={message.content}/>}</div>}</article>}
