import { Link, useNavigate } from "react-router-dom";
import { useState } from "react";
import { signup } from "../../services/authService";
import { normalizeSignupError } from "../../services/authError";
import AuthLayout from "../../layout/AuthLayout";
import Card from "../../components/ui/Card";
import Input from "../../components/ui/Input";
import Button from "../../components/ui/Button";
export default function Signup(){const navigate=useNavigate();const [formData,setFormData]=useState({name:"",email:"",password:""});const [errors,setErrors]=useState({name:"",email:"",password:""});const [loading,setLoading]=useState(false);const [serverError,setServerError]=useState("");const handleChange=e=>{setFormData(prev=>({...prev,[e.target.name]:e.target.value}));setErrors(prev=>({...prev,[e.target.name]:""}));setServerError("")};const handleSubmit=async e=>{e.preventDefault();const newErrors={};if(!formData.name.trim())newErrors.name="Name is required";if(!formData.email.trim())newErrors.email="Email is required";if(!formData.password.trim())newErrors.password="Password is required";if(Object.keys(newErrors).length){setErrors(newErrors);return}try{setLoading(true);await signup(formData);navigate("/login",{state:{accountCreated:true}})}catch(error){setServerError(normalizeSignupError(error))}finally{setLoading(false)}};return <AuthLayout><Card><span className="eyebrow">Begin your research</span><h1>Create account</h1><p>Set up your AskLAW workspace.</p><form onSubmit={handleSubmit}><Input label="Full name" name="name" value={formData.name} onChange={handleChange} placeholder="Your name" error={errors.name}/><Input label="Email address" name="email" type="email" value={formData.email} onChange={handleChange} placeholder="you@example.com" error={errors.email}/><Input label="Password" name="password" type="password" value={formData.password} onChange={handleChange} placeholder="Create a password" error={errors.password} autoComplete="new-password"/>{serverError&&<p className="field-error" role="alert" style={{whiteSpace:"pre-line"}}>{serverError}</p>}<Button type="submit" disabled={loading}>{loading?"Creating account…":"Create account"}</Button></form><div className="auth-switch">Already have an account? <Link className="text-link" to="/login">Sign in</Link></div></Card></AuthLayout>}
