# =========================================================
# ASKLAW AI SERVICE
# =========================================================
#
# Complete answer-generation pipeline.
#
# FLOW:
#
#     USER QUESTION
#           ↓
#     RETRIEVAL ORCHESTRATOR
#           ↓
#      ┌────┼────┐
#      ↓    ↓    ↓
#     RAG  WEB HYBRID
#      └────┼────┘
#           ↓
#     PROMPT SERVICE
#           ↓
#         GROQ
#           ↓
#      STREAM ANSWER
#           ↓
#   BACKEND SOURCE METADATA
#
# IMPORTANT:
#
# Source metadata is generated by the backend.
# The LLM never generates source metadata.
# =========================================================


import asyncio
import json


from groq import Groq


from app.core.config import Settings


from app.services.retrieval_orchestrator import (
    retrieve_for_query,
)


from app.services.prompt_service import (
    build_legal_prompt,
)


# =========================================================
# SETTINGS
# =========================================================

settings = Settings()


# =========================================================
# GROQ CLIENT
# =========================================================

client = Groq(
    api_key=settings.GROQ_API_KEY
)


# =========================================================
# FALLBACK SYSTEM PROMPT
# =========================================================

SYSTEM_PROMPT = """
You are AskLaw, an AI assistant for
educational and informational legal research.

Answer clearly and professionally.

When no source material is available,
do not fabricate legal information.

Responses are for educational and
informational purposes only.

They do not constitute legal advice.
"""


# =========================================================
# BUILD RAG SOURCE METADATA
# =========================================================

def build_sources(
    retrieved_chunks,
):
    """
    Build authoritative metadata from the
    backend RAG retrieval results.

    The LLM does NOT generate this metadata.
    """

    sources = []

    if not retrieved_chunks:
        return sources

    for chunk in retrieved_chunks:

        if not isinstance(
            chunk,
            dict,
        ):
            continue

        source = {
            "document_id": chunk.get(
                "document_id"
            ),

            "filename": chunk.get(
                "filename"
            ),

            "page_number": chunk.get(
                "page_number"
            ),

            "chunk_index": chunk.get(
                "chunk_index"
            ),

            "score": chunk.get(
                "score"
            ),

            "source_type": "document",
        }

        sources.append(
            source
        )

    return sources


# =========================================================
# BUILD WEB SOURCE METADATA
# =========================================================

def build_web_sources(
    web_results,
):
    """
    Build authoritative metadata from the
    web retrieval results.

    The LLM does NOT generate this metadata.
    """

    sources = []

    if not web_results:
        return sources

    for result in web_results:

        if not isinstance(
            result,
            dict,
        ):
            continue

        source = {
            "title": result.get(
                "title",
                "",
            ),

            "url": result.get(
                "url",
                "",
            ),

            "content": result.get(
                "content",
                "",
            ),

            "engine": result.get(
                "engine",
                "",
            ),

            "source_type": "web",
        }

        sources.append(
            source
        )

    return sources


# =========================================================
# FIND USER MESSAGE
# =========================================================

def _get_latest_user_message(
    messages,
):
    """
    Find the latest user message.
    """

    for message in reversed(
        messages
    ):

        if message.role == "user":

            return message.content

    return None


# =========================================================
# STREAM RESPONSE
# =========================================================

def stream_response(
    messages,
    user_id=None,
):
    """
    Complete AskLaw response pipeline.

    1. Extract user question.
    2. Route query.
    3. Retrieve RAG / WEB / HYBRID context.
    4. Build grounded prompt.
    5. Call Groq.
    6. Stream tokens.
    7. Send backend-generated sources.
    8. Send route information.
    """

    # =====================================================
    # FIND USER QUESTION
    # =====================================================

    user_message = (
        _get_latest_user_message(
            messages
        )
    )

    # =====================================================
    # SAFETY CHECK
    # =====================================================

    if not user_message:

        error_event = {
            "type": "error",
            "content": (
                "I couldn't find a user question "
                "to answer."
            ),
        }

        yield (
            json.dumps(
                error_event
            )
            + "\n"
        )

        return

    # =====================================================
    # RETRIEVAL
    # =====================================================

    try:

        # IMPORTANT:
        #
        # retrieve_for_query() expects
        # positional arguments.
        #
        # DO NOT use:
        #
        # retrieve_for_query(
        #     query=user_message,
        #     user_id=user_id
        # )
        #
        # because your current orchestrator does
        # not define user_id as a keyword parameter.

        retrieval_result = (
            asyncio.run(
                retrieve_for_query(
                    user_message,
                    user_id,
                )
            )
        )

    except Exception as exc:

        print()
        print("=" * 60)
        print("ASKLAW RETRIEVAL ERROR")
        print("=" * 60)
        print(
            str(exc)
        )
        print("=" * 60)

        error_event = {
            "type": "error",
            "content": (
                f"Retrieval error: {str(exc)}"
            ),
        }

        yield (
            json.dumps(
                error_event
            )
            + "\n"
        )

        return

    # =====================================================
    # EXTRACT RETRIEVAL RESULTS
    # =====================================================

    route = retrieval_result.get(
        "route",
        "rag",
    )

    rag_results = retrieval_result.get(
        "rag_results",
        [],
    )

    web_results = retrieval_result.get(
        "web_results",
        [],
    )

    # =====================================================
    # DEBUG
    # =====================================================

    print()
    print("=" * 60)
    print("ASKLAW AI PIPELINE")
    print("=" * 60)

    print(
        "QUERY:",
        user_message,
    )

    print(
        "ROUTE:",
        route,
    )

    print(
        "RAG RESULTS:",
        len(rag_results),
    )

    print(
        "WEB RESULTS:",
        len(web_results),
    )

    print("=" * 60)

    # =====================================================
    # BUILD GROUNDED LEGAL PROMPT
    # =====================================================

    try:

        legal_prompt = build_legal_prompt(
            query=user_message,
            route=route,
            rag_results=rag_results,
            web_results=web_results,
        )

    except Exception as exc:

        print()
        print("=" * 60)
        print("ASKLAW PROMPT ERROR")
        print("=" * 60)
        print(
            str(exc)
        )
        print("=" * 60)

        error_event = {
            "type": "error",
            "content": (
                f"Prompt error: {str(exc)}"
            ),
        }

        yield (
            json.dumps(
                error_event
            )
            + "\n"
        )

        return

    # =====================================================
    # BUILD AUTHORITATIVE SOURCES
    # =====================================================

    rag_sources = build_sources(
        rag_results
    )

    web_sources = build_web_sources(
        web_results
    )

    # =====================================================
    # COMBINE SOURCES
    # =====================================================

    sources = (
        rag_sources
        + web_sources
    )

    # =====================================================
    # DEBUG SOURCES
    # =====================================================

    print()
    print(
        "BACKEND SOURCES:",
        len(sources),
    )

    for index, source in enumerate(
        sources,
        start=1,
    ):

        print(
            f"SOURCE {index}:",
            source,
        )

    print("=" * 60)

    # =====================================================
    # BUILD GROQ MESSAGES
    # =====================================================

    if legal_prompt:

        groq_messages = [
            {
                "role": "system",
                "content": legal_prompt,
            },
            {
                "role": "user",
                "content": user_message,
            },
        ]

    else:

        # -------------------------------------------------
        # FALLBACK
        # -------------------------------------------------

        groq_messages = [
            {
                "role": "system",
                "content": SYSTEM_PROMPT,
            },
            {
                "role": "user",
                "content": user_message,
            },
        ]

    # =====================================================
    # CALL GROQ
    # =====================================================

    try:

        stream = (
            client.chat.completions.create(
                model="openai/gpt-oss-120b",

                messages=groq_messages,

                temperature=0.2,

                max_completion_tokens=2048,

                stream=True,
            )
        )

    except Exception as exc:

        print()
        print("=" * 60)
        print("ASKLAW GROQ ERROR")
        print("=" * 60)
        print(
            str(exc)
        )
        print("=" * 60)

        error_event = {
            "type": "error",
            "content": (
                f"AI service error: {str(exc)}"
            ),
        }

        yield (
            json.dumps(
                error_event
            )
            + "\n"
        )

        return

    # =====================================================
    # STREAM GROQ TOKENS
    # =====================================================

    try:

        for chunk in stream:

            if not chunk.choices:
                continue

            content = (
                chunk
                .choices[0]
                .delta
                .content
            )

            if not content:
                continue

            token_event = {
                "type": "token",
                "content": content,
            }

            yield (
                json.dumps(
                    token_event
                )
                + "\n"
            )

    except Exception as exc:

        print()
        print("=" * 60)
        print("ASKLAW STREAM ERROR")
        print("=" * 60)
        print(
            str(exc)
        )
        print("=" * 60)

        error_event = {
            "type": "error",
            "content": (
                f"Streaming error: {str(exc)}"
            ),
        }

        yield (
            json.dumps(
                error_event
            )
            + "\n"
        )

        return

    # =====================================================
    # SEND BACKEND SOURCE METADATA
    # =====================================================
    #
    # IMPORTANT:
    #
    # This is generated by Python.
    #
    # The LLM has absolutely no control over it.
    #
    # =====================================================

    if sources:

        source_event = {
            "type": "sources",
            "sources": sources,
        }

        yield (
            json.dumps(
                source_event
            )
            + "\n"
        )

    # =====================================================
    # SEND ROUTE
    # =====================================================

    route_event = {
        "type": "route",
        "route": route,
    }

    yield (
        json.dumps(
            route_event
        )
        + "\n"
    )

    # =====================================================
    # DEBUG COMPLETE
    # =====================================================

    print()
    print("=" * 60)
    print("ASKLAW AI RESPONSE COMPLETE")
    print("=" * 60)
    print(
        "ROUTE:",
        route,
    )
    print(
        "SOURCES:",
        len(sources),
    )
    print("=" * 60)