# =========================================================
# ASKLAW PROMPT SERVICE
# =========================================================
#
# Builds the final grounded prompt sent to the LLM.
#
# Supported retrieval modes:
#
#   RAG     -> uploaded/local documents only
#   WEB     -> web search results only
#   HYBRID  -> local documents + web results
#
# The prompt service can also consume the structured
# evidence bundle generated by evidence_service.py.
#
# IMPORTANT:
#
# The LLM may ONLY use the source material supplied
# in the prompt.
#
# The LLM must NOT:
#   - use outside legal knowledge
#   - browse the internet
#   - invent facts
#   - invent citations
#   - add unsupported legal provisions
#
# The backend remains responsible for source attribution
# and claim verification.
# =========================================================


# =========================================================
# BUILD RAG CONTEXT
# =========================================================

def _build_rag_context(
    rag_results: list,
) -> str:
    """
    Build context from local RAG results.
    """

    context_parts = []

    for index, chunk in enumerate(
        rag_results,
        start=1,
    ):

        if not isinstance(
            chunk,
            dict,
        ):
            continue

        text = chunk.get(
            "text",
            "",
        )

        if not text:
            continue

        context_parts.append(
            f"""
LOCAL DOCUMENT SOURCE {index}

{text}
"""
        )

    return "\n".join(
        context_parts
    )


# =========================================================
# BUILD WEB CONTEXT
# =========================================================

def _build_web_context(
    web_results: list,
) -> str:
    """
    Build context from web search results.
    """

    context_parts = []

    for index, result in enumerate(
        web_results,
        start=1,
    ):

        if not isinstance(
            result,
            dict,
        ):
            continue

        title = result.get(
            "title",
            "",
        )

        content = result.get(
            "content",
            "",
        )

        url = result.get(
            "url",
            "",
        )

        engine = result.get(
            "engine",
            "",
        )

        if not title and not content:
            continue

        context_parts.append(
            f"""
WEB SEARCH SOURCE {index}

Title:
{title}

Content:
{content}

URL:
{url}

Search engine:
{engine}
"""
        )

    return "\n".join(
        context_parts
    )


# =========================================================
# BUILD STRUCTURED EVIDENCE CONTEXT
# =========================================================

def _build_evidence_context(
    evidence_bundle: dict,
) -> str:
    """
    Build a structured evidence context for the LLM.

    The evidence service has already:
        - normalized evidence
        - classified source types
        - ranked source authority
        - extracted dates
        - identified basic conflict signals

    The LLM may use the evidence text, but the machine-generated
    metadata should not be treated as a substitute for reading
    the source content.
    """

    if not evidence_bundle:
        return ""

    evidence = evidence_bundle.get(
        "evidence",
        [],
    )

    if not evidence:
        return ""

    context_parts = []

    context_parts.append(
        """
==================================================
STRUCTURED EVIDENCE
==================================================

The following evidence was retrieved and normalized
by the AskLaw backend.

Each evidence item has an Evidence ID used internally
by the backend.

Do NOT reproduce Evidence IDs in your answer.

Do NOT create citations or references.

Use the actual evidence text as the factual basis
for your answer.
"""
    )

    for item in evidence:

        if not isinstance(
            item,
            dict,
        ):
            continue

        evidence_id = item.get(
            "evidence_id",
            "",
        )

        source_type = item.get(
            "source_type",
            "general",
        )

        title = item.get(
            "title",
            "",
        )

        url = item.get(
            "url",
            "",
        )

        text = item.get(
            "text",
            "",
        )

        authority_score = item.get(
            "authority_score",
        )

        freshness_score = item.get(
            "freshness_score",
        )

        legal_event_score = item.get(
            "legal_event_score",
        )

        date_metadata = item.get(
            "date_metadata",
            {},
        )

        if not isinstance(
            date_metadata,
            dict,
        ):
            date_metadata = {}

        detected_date = date_metadata.get(
            "date"
        )

        date_source = date_metadata.get(
            "source"
        )

        date_confidence = date_metadata.get(
            "confidence"
        )

        if not text:
            continue

        context_parts.append(
            f"""
--------------------------------------------------
EVIDENCE {evidence_id}
--------------------------------------------------

Source type:
{source_type}

Title:
{title}

URL:
{url}

Detected source date:
{detected_date}

Date source:
{date_source}

Date confidence:
{date_confidence}

Authority signal:
{authority_score}

Freshness signal:
{freshness_score}

Legal-event signal:
{legal_event_score}

Evidence text:
{text}
"""
        )

    # =====================================================
    # MACHINE-DETECTED CONFLICT SIGNALS
    # =====================================================

    conflicts = evidence_bundle.get(
        "conflicts",
        [],
    )

    if conflicts:

        context_parts.append(
            """
==================================================
POTENTIAL EVIDENCE CONFLICT SIGNALS
==================================================

The backend detected the following signals.

IMPORTANT:

These are NOT conclusions that the sources are
actually contradictory.

They are only indicators that deserve careful
comparison of the underlying evidence.
"""
        )

        for conflict in conflicts:

            if not isinstance(
                conflict,
                dict,
            ):
                continue

            context_parts.append(
                f"""
Conflict signal type:
{conflict.get("type")}

Evidence IDs:
{conflict.get("evidence_ids")}

Signal score:
{conflict.get("score")}

Reason:
{conflict.get("reason")}
"""
            )

    return "\n".join(
        context_parts
    )


# =========================================================
# BUILD FINAL LEGAL PROMPT
# =========================================================

def build_legal_prompt(
    query: str,
    retrieved_chunks: list | None = None,
    *,
    route: str = "rag",
    rag_results: list | None = None,
    web_results: list | None = None,
    evidence_bundle: dict | None = None,
):
    """
    Build a strictly source-grounded legal prompt.

    Parameters
    ----------
    query:
        User's legal question.

    retrieved_chunks:
        Backward-compatible argument for old RAG callers.

    route:
        rag | web | hybrid

    rag_results:
        Local RAG results.

    web_results:
        Web search results.

    evidence_bundle:
        Structured evidence bundle from evidence_service.py.

    Returns
    -------
    str
        Final grounded prompt.
    """

    # =====================================================
    # BACKWARD COMPATIBILITY
    # =====================================================

    if rag_results is None:

        rag_results = (
            retrieved_chunks
            if retrieved_chunks is not None
            else []
        )

    if web_results is None:
        web_results = []

    # =====================================================
    # NORMALIZE ROUTE
    # =====================================================

    route = (
        route or "rag"
    ).lower().strip()

    if route not in {
        "rag",
        "web",
        "hybrid",
    }:
        route = "rag"

    # =====================================================
    # BUILD SOURCE MATERIAL
    # =====================================================

    if evidence_bundle:

        structured_context = (
            _build_evidence_context(
                evidence_bundle
            )
        )

    else:

        rag_context = _build_rag_context(
            rag_results
        )

        web_context = _build_web_context(
            web_results
        )

        context_parts = []

        if rag_context:

            context_parts.append(
                """
==================================================
LOCAL DOCUMENT MATERIAL
==================================================

The following material comes from the user's
uploaded/local documents.

Use it as document-grounded source material.

""" + rag_context
            )

        if web_context:

            context_parts.append(
                """
==================================================
WEB SEARCH MATERIAL
==================================================

The following material comes from web search.

Use it ONLY when answering claims supported
by this web-search material.

Do NOT treat web search material as part of the
uploaded/local documents.

""" + web_context
            )

        structured_context = "\n".join(
            context_parts
        )

    # =====================================================
    # NO SOURCE MATERIAL
    # =====================================================

    if not structured_context.strip():

        structured_context = """
No usable SOURCE MATERIAL was retrieved.
"""

    # =====================================================
    # FINAL GROUNDED PROMPT
    # =====================================================

    prompt = f"""
You are AskLaw, an AI assistant for
educational and informational legal research.

Your task is to answer the user's question using
ONLY the SOURCE MATERIAL provided below.

==================================================
ABSOLUTE GROUNDING RULE
==================================================

The SOURCE MATERIAL is your ONLY factual source.

You MUST NOT use:

- your general knowledge
- your training knowledge
- information from memory
- information not present in the SOURCE MATERIAL
- assumptions
- guesses
- speculation

Do NOT browse the internet.

Every factual statement in your answer must be
supported by the SOURCE MATERIAL.

==================================================
RETRIEVAL MODE
==================================================

The current retrieval mode is:

{route}

Possible modes are:

- rag
- web
- hybrid

Do not assume that information exists merely
because the retrieval mode suggests it might.

Use only the actual SOURCE MATERIAL below.

==================================================
EVIDENCE HIERARCHY
==================================================

When multiple sources provide information:

1. Prefer primary legal source material when it
   directly answers the question.

2. Prefer exact legal text over summaries when
   exact legal text is available.

3. Use legal reporting for developments or
   reporting that are actually present in the
   supplied source material.

4. Use commentary for explanation only when the
   information is supported by that commentary.

5. Do not treat source authority metadata as proof
   of a legal proposition.

6. Read the actual evidence text before stating
   a factual proposition.

==================================================
SOURCE DATES
==================================================

Some evidence may contain a detected source date.

A detected source date is the date associated with
the retrieved source/article/result.

It is NOT automatically the date of a judgment,
order, case, or legal event.

Do not convert a detected publication/update date
into a court-event date unless the SOURCE MATERIAL
explicitly supports that interpretation.

==================================================
DO NOT INVENT INFORMATION
==================================================

Never invent or add:

- laws
- Articles
- sections
- clauses
- constitutional provisions
- court decisions
- cases
- judgments
- legal procedures
- penalties
- punishments
- exceptions
- definitions
- dates
- legal interpretations
- legal consequences
- court powers
- legal terminology

unless explicitly supported by the SOURCE MATERIAL.

==================================================
ANSWER THE EXACT QUESTION
==================================================

Answer the question that the user actually asked.

Do not answer a different related question.

If the user asks for a list:
provide the supported list.

If the user asks for a definition:
provide the supported definition.

If the user asks for an explanation:
explain only what the source supports.

If the source contains only partial information:
provide only that partial information.

==================================================
SOURCE SEPARATION
==================================================

LOCAL DOCUMENT MATERIAL and WEB SEARCH MATERIAL
are separate sources.

Do NOT pretend that web search information came
from the uploaded/local documents.

Do NOT pretend that uploaded/local document
information came from the web.

For hybrid questions, keep the distinction between
these materials clear.

==================================================
ARTICLE-SPECIFIC QUESTIONS
==================================================

If the user asks about a specific Article,
section, clause, or provision:

1. Prefer SOURCE MATERIAL that directly contains
   that provision.

2. Stay focused on the provision asked about.

3. Do NOT introduce another Article simply
   because it is related.

4. Do NOT introduce another section or provision
   unless the SOURCE MATERIAL explicitly makes it
   necessary for the answer.

5. Do NOT combine unrelated provisions to create
   a new legal conclusion.

6. Do NOT use your own knowledge to connect
   different provisions.

==================================================
EXAMPLE: ARTICLE 32
==================================================

Suppose the user asks:

"What writs can the Supreme Court issue
under Article 32?"

If the SOURCE MATERIAL contains Article 32 and
states that the Supreme Court has power to issue
writs including:

- habeas corpus
- mandamus
- prohibition
- quo warranto
- certiorari

then simply provide those supported writs.

Do NOT introduce another Article.

Do NOT explain another Article.

Do NOT use outside information to expand the answer.

The answer must remain focused on the material
provided for the user's question.

==================================================
CURRENT / LATEST QUESTIONS
==================================================

When the user asks for latest, recent, current,
new, or updated information:

Use the supplied recent/current evidence where it
actually supports the requested subject.

Do NOT assume that the newest publication date
means the newest judgment.

Do NOT assume that a recent article discusses a
recent legal event.

For a request specifically asking for a latest
judgment, ruling, or order, distinguish carefully
between:

- an actual primary legal document,
- reporting about that legal event,
- commentary about an older legal event.

Only state that something is the latest judgment,
ruling, or order when the SOURCE MATERIAL itself
supports that characterization.

==================================================
POTENTIAL SOURCE CONFLICTS
==================================================

The backend may provide potential conflict signals.

These are machine-generated retrieval signals.

They are NOT automatically proof that sources
actually disagree.

If the supplied source material explicitly presents
different legal positions, distinguish them clearly.

Do not resolve a legal disagreement using your own
knowledge.

Do not pretend that two sources agree when their
supplied text differs materially.

==================================================
WEB SEARCH RULE
==================================================

Web search results are SOURCE MATERIAL.

However, only use information that is actually
present in the supplied web-search results.

Do NOT fill gaps using your own knowledge.

If a web result only provides a short summary,
do not expand that summary using outside knowledge.

==================================================
PARTIAL INFORMATION
==================================================

If SOURCE MATERIAL contains only part of the
requested information, provide only the supported
part.

Do NOT complete the answer using general
legal knowledge.

Do NOT assume missing information.

Do NOT reconstruct omitted text.

==================================================
WHEN INFORMATION IS MISSING
==================================================

If SOURCE MATERIAL does not contain enough
information to answer a requested part, say:

"The provided documents do not contain enough
information to answer that part of the question."

Do not guess.

Do not speculate.

Do not provide an outside-knowledge answer.

==================================================
EXPLANATIONS
==================================================

You may simplify legal language that is explicitly
present in SOURCE MATERIAL.

However, your explanation must preserve the
meaning of the source.

Do NOT add:

- new legal facts
- outside interpretations
- unstated consequences
- unstated exceptions
- additional legal provisions

==================================================
ARTICLE REFERENCES
==================================================

You may mention an Article number only when:

1. It appears in the user's question, OR

2. It appears explicitly in the SOURCE MATERIAL.

Do NOT introduce Article numbers from your own
knowledge.

==================================================
SOURCE CITATIONS
==================================================

DO NOT generate source citations.

DO NOT mention:

- source numbers
- chunk numbers
- backend Evidence IDs
- internal ranking scores
- internal authority scores
- internal freshness scores

unless the user explicitly asks about how AskLaw
retrieves or verifies evidence.

The backend is responsible for source attribution.

Do NOT create:

- "Source:" sections
- "References:" sections
- citations
- bibliography sections

==================================================
ANSWER STYLE
==================================================

Keep the answer clear and concise.

Use bullet points or numbered lists when
appropriate.

Use simple language when explaining the
provided material.

Do not unnecessarily repeat source text.

Do not add unsupported legal conclusions.

==================================================
USER QUESTION
==================================================

{query}

==================================================
SOURCE MATERIAL
==================================================

{structured_context}

==================================================
FINAL GROUNDING CHECK
==================================================

Before producing the answer, internally check:

1. Is every factual statement supported by
   SOURCE MATERIAL?

2. Did I use general legal knowledge?

3. Did I invent legal information?

4. Did I introduce an Article that is not
   necessary?

5. Did I introduce another legal provision?

6. Did I use unrelated source material?

7. Did I add an unsupported interpretation?

8. Did I add an unsupported legal consequence?

9. Did I invent a citation?

10. Did I mention internal evidence IDs?

11. Did I create a Sources or References section?

12. Did I confuse local document material
    with web search material?

13. Did I mistake an article publication/update
    date for the date of a judgment?

14. Did I call something the latest judgment
    without SOURCE MATERIAL supporting that?

If any statement is unsupported,
REMOVE THAT STATEMENT.

If the source is insufficient, say:

"The provided documents do not contain enough
information to answer that part of the question."

==================================================
DISCLAIMER
==================================================

This response is for educational and
informational purposes only.

It does not constitute legal advice and should
not be treated as a substitute for advice from
a qualified lawyer.

==================================================
FINAL INSTRUCTION
==================================================

Answer the user's question now.

Use ONLY the SOURCE MATERIAL.

Do NOT use outside knowledge.

Do NOT browse the internet.

Do NOT hallucinate.

Do NOT invent legal information.

Do NOT introduce unrelated Articles.

Do NOT cross-reference another legal provision
unless the SOURCE MATERIAL explicitly supports it.

Do NOT generate citations.

Do NOT generate a Sources section.

Do NOT generate a References section.

Do NOT expose internal evidence IDs or ranking metadata.
"""

    return prompt